### ISSUE TITLE
Changing minDistance manually crashes the app

### ISSUE THREAD

**Issue by WebMaestroFr** [WebMaestroFr/planets#30]

**Comment by kchapelier** [comment]
The issue probably happens when a minDistance of 0 is given to poisson-disk-sampling. Apparently Blueprint's NumericInput doesn't enforce its constraints (_min={0.01}_) on manual inputs as it solely rely on the browser implementation of _input type="number"_. A quick fix would be to clamp the minDistance value in [tile.ts](https://github.com/WebMaestroFr/planets/blob/fe356c65d74cc7d6843188e305864524d91014de/src/hooks/tiles.ts#L33).

**Comment by WebMaestroFr** [comment]
Thanks for the tip, I did just that ;)
